# Generated by Django 5.0.7 on 2024-07-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_alter_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fare_per_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
